### ISSUE TITLE
Trusty fails

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#33]

**Comment by rgleason** [comment]
https://app.circleci.com/pipelines/github/jongough/testplugin_pi/264/workflows/82845b02-d197-4aa4-9a41-4f319e6947ff/jobs/1052

```
+ '[' true ']'
+ pyenv versions
/home/circleci/project/build/cloudsmith-upload.sh: line 54: pyenv: command not found
+ dnf --version
/home/circleci/project/build/cloudsmith-upload.sh: line 62: dnf: command not found
+ apt-get --version
+ COUNTER=0
+ sudo apt-get install python3-pip python3-setuptools
Reading package lists... Done
Building dependency tree       
```
Further down.
```
+ sudo python3 -m pip install -q cloudsmith-cli
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map
During handling of the above exception, another exception occurred:
```

**Comment by rgleason** [comment]
Here is a trusty that does build, same as oesenc
https://github.com/rgleason/squiddio_pi/blob/ci/ci/circleci-build-trusty.sh

**Comment by jongough** [comment]
I am not sure what is going on with the Trusty environment. I have tried the same commands on a clean Ubuntu 16.04 system and it works fine.
Just done a build and Trusty is now working, not sure why.

**Comment by rgleason** [comment]
Weird, but good.  Closing
